### ISSUE TITLE
Email Configuration is not working

### ISSUE THREAD

**Issue by naveen-fractlio** [fractalio/integralstor_gridcell#108]
For configuring the Email settings, after all inputs the page simply flashes and reloads.

recreation steps:

services >> configure email >> save

screenshots:

![screenshot from 2016-01-13 10-12-15](https://cloud.githubusercontent.com/assets/11418556/12285323/f5609936-b9de-11e5-8cd8-386c503d5a05.png)
![screenshot from 2016-01-13 10-13-53](https://cloud.githubusercontent.com/assets/11418556/12285324/f56131a2-b9de-11e5-8b7d-5eea88523fb7.png)

**Comment by fractalram** [comment]
Form field name problem. shd be ok now

**Comment by naveen-fractlio** [comment]
E-mail configurations are working fine so closing this issue.
