### ISSUE TITLE
iSCSI Initiator fialed to discover target portal for windows

### ISSUE THREAD

**Issue by naveen-fractlio** [fractalio/integralstor_gridcell#110]
The iSCSI Initiator fialed to discover target portal for windows7. saying "The iSCSI name specified contains invalid charecter or is too long"

*recreating steps:
1. At target server side:
    shares and targets >> create new iSCSI target >> edit particular target and change the target/initiator credentials as per the need.
2. At initiator/client side(here windows7):
    launch iSCSI Initiator app(satrt menu) >> in ISCSI inititor properties, select Discovery tab >> press discover portal >> enter trgt IP address or DNS and press ok >> "error popup window"

screenshot:

![screenshot from 2016-01-13 10-52-05](https://cloud.githubusercontent.com/assets/11418556/12286017/770361ce-b9e6-11e5-80ae-15c363f934aa.png)

**Comment by fractalram** [comment]
Changed the underscore to a hyphen so shd fix the problem.

**Comment by naveen-fractlio** [comment]
Its fixed under tag g1.1.1.rc1 and same is tested and verified so marking it as closed.
