### ISSUE TITLE
Adding iSCSI initiator/target users after remove, with same username is giving error.

### ISSUE THREAD

**Issue by naveen-fractlio** [fractalio/integralstor_gridcell#111]
In iSCSI Targets, after all valid inputs/changes, the target is able to detect from the initiators. But once after removing the corresponding 'initiator authentication user' and 'target authentication user' from target, and if u try to add 'add initiator authentication user' and 'add target authentication user' with same username as before is giving error saying ...

"Error adding ISCSI authentication user

Error Details : Error Adding User: tgtadm: this account already exists "

 which causes the target is not accessible at the initiator side!!!

recreation steps:
shares and targets >> create new iSCSI target >> edit target >> add LUN and add ACL >> add initiator and target auth users >> save changes >> select view iSCSI targets >> edit target >> remove auth. init. user and remove auth. targ. user >> edit again iscsi target >> try to adauth. init. user and auth. tag user with ''same username" as previous. >> error!!!

screenstots:

![screenshot from 2016-01-13 16-58-59](https://cloud.githubusercontent.com/assets/11418556/12293438/9202f1d2-ba19-11e5-9bad-8964345d265b.png)
![screenshot from 2016-01-13 16-59-11](https://cloud.githubusercontent.com/assets/11418556/12293439/92043e52-ba19-11e5-80c5-4bc74ec03d74.png)

**Comment by fractalram** [comment]
This is a quirk of istgt - even though the user is deleted from the target, it still exists in istgt. Restarting the iscsi service should clear this. If that works, then this bug can be marked wontfix.

**Comment by naveen-fractlio** [comment]
Yes after restarting iscsi service(service tgtd restart) it will allow to create user with same name.
