### ISSUE TITLE
Under 'shares and targets' tab, the 'allowed users' in edit share and the 'permitted users' in create new shares listing out only numbers!!!

### ISSUE THREAD

**Issue by naveen-fractlio** [fractalio/integralstor_gridcell#112]
![screenshot from 2016-01-13 17-57-30](https://cloud.githubusercontent.com/assets/11418556/12294289/2d73d2c6-ba1f-11e5-8871-e76627f90873.png)
![screenshot from 2016-01-13 17-57-40](https://cloud.githubusercontent.com/assets/11418556/12294290/2d75144c-ba1f-11e5-8427-97ec21c2cc78.png)

This happens when the UserID is numbers instead charecters as it reads userid and displays.
Better to read userid with name also or only the username.

**Comment by fractalram** [comment]
This has been fixed in version g1.1.1.rc1. Cannot create a user whose username begins with a number now..

**Comment by naveen-fractlio** [comment]
Its verified under tag g1.1.1.rc2 . So closing this issue.
