### ISSUE TITLE
Added Gridcells are not displayed in Gridcell information! under Gridcells

### ISSUE THREAD

**Issue by naveen-fractlio** [fractalio/integralstor_gridcell#115]
apart from primary and secondary one gridcell was there as part of the storage pool. After adding remaining 5gridcell, the gridcells added are not showing in the info.

**Comment by fractalram** [comment]
Have changed the checkbox to a radio button so that they can only add one at a time. This will (hopefully!) prevent a browser timeout so that they can see the result.

**Comment by naveen-fractlio** [comment]
On adding new gridcell, its giving error saying "Error adding GRIDCells to the grid : Error retrieving the IP from GRIDCell gridcell-f5c4.integralstor.lan : Error retrieving minion IP address : Could not retrieve the IP for GRIDCell gridcell-f5c4.integralstor.lan Error retrieving the IP from GRIDCell gridcell-f5c4.integralstor.lan : Error retrieving minion IP address : Could not retrieve the IP for GRIDCell gridcell-f5c4.integralstor.lan "

recreating steps:
gridcells >> scan for new gridcells >> select and add any one gridcell >> error(after few mins)

screenshot:
![screenshot from 2016-01-19 15-49-40](https://cloud.githubusercontent.com/assets/11418556/12416411/686bef42-bec7-11e5-97cf-24d6642c955b.png)

**Comment by naveen-fractlio** [comment]
This is working fine so closing the issue.
