### ISSUE TITLE
CIFS Share fails after restoring a snapshot

### ISSUE THREAD

**Issue by ramaseshan** [fractalio/integralstor_gridcell#118]
Problem : A CIFS share dosent authenticate, after a we restore the snapshot of a volume and try to access the same share again

Steps to Reproduce : 
1. Create a Volume
2. Create a few users
3. Make a snapshot of the volume
4. Try to access the share before/after the snapshot.
5. Restore the snapshot.
6. On successful restoration, try to access the share, and it dosent authenticate the user (not any user).

**Comment by fractalram** [comment]
Does restarting samba after the snapshot has been restored, fix this problem?

**Comment by naveen-fractlio** [comment]
No. after restarting samba problem still exist.
I recreated it now.
Even changing permission from user to guest after this problem giving same error.

"The network cannot be found"

**Comment by ramaseshan** [comment]
This bug dosent seem to be reproducible.
What we have to make sure is, after restoring the snapshot, we also start the volume and then try accessing the share

**Comment by naveen-fractlio** [comment]
Its fixed and working OK. So closing this issue.
