### ISSUE TITLE
cifs share quota information is still showing full capacity instead of allocated quota.

### ISSUE THREAD

**Issue by naveen-fractlio** [fractalio/integralstor_gridcell#119]
After implementing the 'set directory quota' its not showing allocated quota info. on client side.
Need to set " gluster volume set vol_name quota-deem-statfs on " for these directory created.

screenshot:

![desktop 1_003](https://cloud.githubusercontent.com/assets/11418556/15708982/c3455374-281f-11e6-8bd2-ee6096b5511b.png)

**Comment by ramaseshan** [comment]
Same as #129 .

**Comment by naveen-fractlio** [comment]
Its fixed marking closed.
