### ISSUE TITLE
Quota size visible under windows share properties

### ISSUE THREAD

**Issue by gattupally** [fractalio/integralstor_gridcell#129]
Quota settings size not visible under windows OS share properties it is visible total unit size.

**Comment by fractalram** [comment]
Naveen, was this reproducible in the latest build?

**Comment by naveen-fractlio** [comment]
@gattupally We found an issue regarding this will fix it.

@fractalram We missed quota enabling flag in volume_management.py

**Comment by fractalram** [comment]
Raju, the issue is with the version that we are testing against. It is fixed in the new build. We will let you know when a new build is ready with all these changes.

**Comment by ramaseshan** [comment]
I am not seeing this issue on the new build. So closing the issue for now.
If this issue persists later on a newer build too, then re-open this issue (and not create a new one)

**Comment by fractalram** [comment]
Reopening now so that it can be confirmed in a release candidate build and then closed.

**Comment by naveen-fractlio** [comment]
This issue is fixed under tag #g1.1.1.rc1
![desktop 1_005](https://cloud.githubusercontent.com/assets/11418556/16037812/d953e020-323f-11e6-8bfa-79605e393fae.png)

**Comment by naveen-fractlio** [comment]
Here the share name should be small, as much as possible(say less than 12-14 charecters) to display the quota size on screen at windows side. 

Because the windows reports mapped drive details on screen is restricted to 3 lines. So if share name is begger means there is chance that the line size pushed to 3 to 4 lines and its not able to diaply.

**Comment by naveen-fractlio** [comment]
Its verified under tag g1.1.1.rc2.
Screens:
![desktop 1_006](https://cloud.githubusercontent.com/assets/11418556/16107688/9402e61a-33bb-11e6-83e3-f691dcac56fe.png)

**Comment by gattupally** [comment]
Quota settings size showing fine, tested in GRIDCell version g1.1.1.rc2.
![directory quota details](https://cloud.githubusercontent.com/assets/7625595/16115801/ffa0434c-33e6-11e6-9441-7c42c0b9270f.jpg)
