### ISSUE TITLE
Scheduling ZFS Scrub wouldnt run

### ISSUE THREAD

**Issue by ramaseshan** [fractalio/integralstor_gridcell#132]
When we schedule a  ZFS Scrub, the scheduler dosent execute.

**Comment by ramaseshan** [comment]
When we are scheduling a scrub, the node column instead of the node name, is taking up a time stamp.

**Comment by ramaseshan** [comment]
#6a537dc5fb6970fb4113e35d26627c53958ef6b2 Should fix this

**Comment by naveen-fractlio** [comment]
Its fixed under tag g1.1.1.rc1

**Comment by naveen-fractlio** [comment]
Its verified under tag g1.1.1.rc2. So closing this issue.

Screenshots:
1. In progress;
![scrub_process](https://cloud.githubusercontent.com/assets/11418556/16107468/351dd3cc-33ba-11e6-8674-473e70e96bff.png)
2. Complete;
![scrub_complete](https://cloud.githubusercontent.com/assets/11418556/16107469/351ddd04-33ba-11e6-8c74-fa4e8f8ea993.png)
